### ISSUE TITLE
Date formatting fails on some Android devices

### ISSUE THREAD

**Issue by GrahamBorland** [ThreeTen/threetenbp#50]
I haven't been able to reproduce this myself, but I am getting reports from the wild that sometimes `LocalDate.format()` is returning an invalid result on some Android devices. (Using https://github.com/JakeWharton/ThreeTenABP.)

Here's what happens, as confirmed by the log call in this method. 
- On entry to this method, `month` is `2016-08`.
- `startOfMonth` is correctly set to `2016-08-01`.
- `monthString` gets set to `0000-00-00` which is wrong.

``` java
private Observable<Void> ensureDataForMonthExistsInternal(YearMonth month) {
    final LocalDate startOfMonth = month.atDay(1);
    final String    monthString  = startOfMonth.format(DateTimeFormatter.ISO_LOCAL_DATE);
    Timber.i("Calling ensureDataForMonthExists with month %s, as date %s, formatted %s", month, startOfMonth, monthString);
```

So far the issue seems to affect only Motorola devices running Android 6.0.

Does threetenbp actually use possibly-broken system APIs for date formatting? Or is it completely self-contained? Intuitively, my expectation is that using `DateTimeFormatter.ISO_LOCAL_DATE` should not require the locale or any other information to be read from the system.

This was originally reported as https://github.com/JakeWharton/ThreeTenABP/issues/33.

**Comment by jodastephen** [comment]
The code in `DateTimeFormatterBuilder` L2352 gets the value, but it just does this by querying the input temporal. So, I can see no reason why it would return zero. Without the ability to reproduce, there isn't much I can do here.

**Comment by slesinskik** [comment]
We are experiencing a very similar issue with `org.threeten:threetenbp:1.3.1`.
So far, we had one error report coming from Motorola Moto G3 running Android 6.0.0.

We are using the following (simplified for readability) code to display dates:
```java
ZonedDateTime now = ZonedDateTime.now();
ZonedDateTime[] datesToDisplay = new ZonedDateTime[8];
for (int i = 0; i < datesToDisplay.length; i++) {
    datesToDisplay[i] = now.plusDays(i);
}
```
We are using the following code to get `day-of-week` (text):
```java
datesToDisplay[i].format(DateTimeFormatter.ofPattern("EE"));
```
And the following code to get `day-of-month` (number) and `month-of-year` (text):
```java
datesToDisplay[i].format(DateTimeFormatter.ofPattern("d MMM"));
```

`Day-of-week` and `month-of-year` values are formatted correctly.
`Day-of-month` always outputs `0`.
Since `day-of-week` is displayed correctly, I assume the problem might be somewhere in `day-of-month` formatting:

![cqr0h-qweaaipfy](https://cloud.githubusercontent.com/assets/4570192/17998859/b1db23a8-6b76-11e6-8902-7c7d981e2b41.jpg)

We might try to get our hands on Moto G3 device to reproduce this issue.

**Comment by gborland** [comment]
My workaround for this is simply to call `LocalDate.toString()` instead of formatting with `DateTimeFormatter.ISO_LOCAL_DATE`.

@jodastephen Is this a safe workaround? Do you think that `LocalDate.toString()` will ever return the date in a different format from the current `uuuu-MM-dd`?

**Comment by jodastephen** [comment]
That workaround is safe,  the toString format will not change

**Comment by riggaroo** [comment]
Hi, 
I was able to reproduce this on a Motorola running 6.0 randomly a few times (which makes me think its a race condition).
This was happening with either of these lines of code: 
```java
String isoTime = LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME);
String formatted = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy"));
```
It seems like it is a race condition though, because the crash doesn't happen when I attach the debugger, but happens when I just run the app. 
It is interesting because running the following line first logs the date correctly:
```java
Log.d(TAG, "onCreate: local date :" + LocalDateTime.now());
```
Logs: 
MainActivity_Test: onCreate: local date :2016-09-05T12:03:37.201

The stack track below is when either one of the two calls above fail. It is also interesting because sometimes it was crashing with HourOfDay and sometimes with DayOfMonth:
```java
FATAL EXCEPTION: main  Process: za.co.riggaroo.dummydates, PID: 20456                                                                           
java.lang.RuntimeException: Unable to start activity ComponentInfo{za.co.riggaroo.dummydates/za.co.riggaroo.dummydates.MainActivity}: org.threeten.bp.DateTimeException: Field HourOfDay cannot be printed as the value 1893747400 exceeds the maximum print width of 2                                                                             
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)                                                                             
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)                                                                             
   at android.app.ActivityThread.-wrap11(ActivityThread.java)                                                                             
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)                                                                             
   at android.os.Handler.dispatchMessage(Handler.java:102)                                                                             
   at android.os.Looper.loop(Looper.java:148)                                                                             
   at android.app.ActivityThread.main(ActivityThread.java:5443)                                                                             
   at java.lang.reflect.Method.invoke(Native Method)                                                                             
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)                                                                             
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)                                                                             
Caused by: org.threeten.bp.DateTimeException: Field HourOfDay cannot be printed as the value 1893747400 exceeds the maximum print width of 2                                                                             
   at org.threeten.bp.format.DateTimeFormatterBuilder$NumberPrinterParser.print(DateTimeFormatterBuilder.java:2361)                                                                             
   at org.threeten.bp.format.DateTimeFormatterBuilder$CompositePrinterParser.print(DateTimeFormatterBuilder.java:1995)                                                                             
   at org.threeten.bp.format.DateTimeFormatterBuilder$CompositePrinterParser.print(DateTimeFormatterBuilder.java:1995)                                                                             
   at org.threeten.bp.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1385)                                                                             
   at org.threeten.bp.format.DateTimeFormatter.format(DateTimeFormatter.java:1359)                                                                             
   at org.threeten.bp.chrono.ChronoLocalDateTime.format(ChronoLocalDateTime.java:263)                                                                             
   at org.threeten.bp.LocalDateTime.format(LocalDateTime.java:1828)                                                                             
   at za.co.riggaroo.dummydates.MainActivity.onCreate(MainActivity.java:24)                                                                             
   at android.app.Activity.performCreate(Activity.java:6245)                                                                             
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)                                                                             
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)                                                                             
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)                                                                              
   at android.app.ActivityThread.-wrap11(ActivityThread.java)                                                                              
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)                                                                              
   at android.os.Handler.dispatchMessage(Handler.java:102)                                                                              
   at android.os.Looper.loop(Looper.java:148)                                                                              
   at android.app.ActivityThread.main(ActivityThread.java:5443)                                                                              
   at java.lang.reflect.Method.invoke(Native Method)                                                                              
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)                                                                              
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by RomainPiel** [comment]
Just connecting the dots (if it can be any helpful), I've reported the same issue there: http://stackoverflow.com/questions/35043000/motorola-devices-org-threeten-bp-datetimeexception-when-parsing-a-date-in-thre
I thought it was correctly reported in that other issue #39 which is now fixed. But at the end it doesn't look like the same problem. #39 is about `ofEpochDay()` whereas this one is around `format()`.

**Comment by riggaroo** [comment]
Some more information that might be useful. Getting the values separately works, as soon as I call format, it breaks.
```java
  LocalDateTime localDateTime = LocalDateTime.now();
        Log.d(TAG, "getDayOfMonth(): " + localDateTime.getDayOfMonth() + ". getYear(): " + localDateTime
                .getYear() + ". getMonth(): " + localDateTime.getMonth() + ". getMonthValue(): " + localDateTime
                .getMonthValue());

        Log.d(TAG, "LocalDateTime.now(): " + LocalDateTime.now());
        final TextView textViewDate = (TextView) findViewById(R.id.text_view_date);

        String isoTime = LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME);
```
Produces the following as a log:
```java

09-05 13:56:13.421 2497-2497/za.co.riggaroo.dummydates D/MainActivity_Test: getDayOfMonth(): 5. getYear(): 2016. getMonth(): SEPTEMBER. getMonthValue(): 9
09-05 13:56:13.421 2497-2497/za.co.riggaroo.dummydates D/MainActivity_Test: LocalDateTime.now(): 2016-09-05T13:56:13.421
09-05 13:56:13.430 2497-2497/za.co.riggaroo.dummydates E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: za.co.riggaroo.dummydates, PID: 2497
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{za.co.riggaroo.dummydates/za.co.riggaroo.dummydates.MainActivity}: org.threeten.bp.DateTimeException: Field MonthOfYear cannot be printed as the value 1893747400 exceeds the maximum print width of 2
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                          Caused by: org.threeten.bp.DateTimeException: Field MonthOfYear cannot be printed as the value 1893747400 exceeds the maximum print width of 2
                                                                             at org.threeten.bp.format.DateTimeFormatterBuilder$NumberPrinterParser.print(DateTimeFormatterBuilder.java:2361)
                                                                             at org.threeten.bp.format.DateTimeFormatterBuilder$CompositePrinterParser.print(DateTimeFormatterBuilder.java:1995)
                                                                             at org.threeten.bp.format.DateTimeFormatterBuilder$CompositePrinterParser.print(DateTimeFormatterBuilder.java:1995)
                                                                             at org.threeten.bp.format.DateTimeFormatterBuilder$CompositePrinterParser.print(DateTimeFormatterBuilder.java:1995)
                                                                             at org.threeten.bp.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1385)
                                                                             at org.threeten.bp.format.DateTimeFormatter.format(DateTimeFormatter.java:1359)
                                                                             at org.threeten.bp.chrono.ChronoLocalDateTime.format(ChronoLocalDateTime.java:263)
                                                                             at org.threeten.bp.LocalDateTime.format(LocalDateTime.java:1828)
                                                                             at za.co.riggaroo.dummydates.MainActivity.onCreate(MainActivity.java:32)
                                                                             at android.app.Activity.performCreate(Activity.java:6245)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

I'm not sure what other information would be useful?

**Comment by jodastephen** [comment]
In your test case, you call `LocalDateTime.now()` multiple times. I suspect that if you use `localDateTime.format(DateTimeFormatter.ISO_DATE_TIME);` on the last line, you won't find a failure until you see the previous two lines fail as well.  ie. [this answer](http://stackoverflow.com/a/35105115/38896) is probably correct. (ie. the result from `System.currentTimeMillis()` is incorrect, but the library isn't correctly validating it).

You can ensure that the object is created correctly by writing your own implementation of `Clock` that ensures that the result of `System.currentTimeMillis()` is sensible before returning it. You would then use `LocalDateTime.now(MyValidatingClock.INSTANCE)` to create the date/time.

**Comment by jodastephen** [comment]
In your test case, you call `LocalDateTime.now()` multiple times. I suspect that if you use `localDateTime.format(DateTimeFormatter.ISO_DATE_TIME);` on the last line, you won't find a failure until you see the previous two lines fail as well.  ie. [this answer](http://stackoverflow.com/a/35105115/38896) is probably correct. (ie. the result from `System.currentTimeMillis()` is ridiculously incorrect, but the library isn't correctly validating against it).

You can ensure that the object is created correctly by writing your own implementation of `Clock` that ensures that the result of `System.currentTimeMillis()` is sensible before returning it. You would then use `LocalDateTime.now(MyValidatingClock.INSTANCE)` to create the date/time.

**Comment by riggaroo** [comment]
Hi @jodastephen 
I realised that I should have done that in the first example, I have updated the previous comment (I think a bit prior to your latest comment). 
The issue still persists when using the same instance of LocalDateTime. I can correctly get all the information and only when running format() the exception does get thrown. 

It looks like it is caused by app installation + race condition though which is strange. 🤔😮

**Comment by riggaroo** [comment]
I am also using version 1.3.2 where I see the Epoch issue might have been fixed? So it is possibly not related to #39

**Comment by jodastephen** [comment]
You may need to compile ThreeTen-Backport yourself with some extra debug statements in the code. Fundamentally, the formatter just uses [this code](https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/LocalDateTime.java#L626) which calls [this code](https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/LocalDate.java#L565) which is a simple switch statement, so if the year/month/day is correct when printed separately, there is probably something wrong with the JVM implementation on that phone.

**Comment by benpm** [comment]
I figured I'd add some information about my own experience with this issue.

We're getting user reports of zeroes appearing instead of expected values. That is, instead of seeing "Sep 6" we see "Sep 0", and instead of "2016-09-06" we see "0000-00-00".

Whether or not this problem is exhibited seems to be determined at app installation time. For both our real-world production app and for a small test app I wrote, the reproduction rate is either 0% or 100% for each installation; bad installations seem to happen 5-10% of the time (though the number of trials is pretty small).

The test app simply creates a `LocalDateTime` object and then sets some `TextView`s to display various bits of the date/time. As a sanity check, it also does the same with a Joda object.

    private void runOnce() {
        org.threeten.bp.LocalDateTime threetenDate = org.threeten.bp.LocalDateTime.now();
        printThreeten(threetenMonth, "MMMM", threetenDate);
        printThreeten(threetenMonthNumeric, "MM", threetenDate);
        printThreeten(threetenDay, "EEEE", threetenDate);
        printThreeten(threetenDayNumeric, "dd", threetenDate);
        printThreeten(threetenYear, "yyyy", threetenDate);
        printThreeten(threetenTime, "HH:mm:ss", threetenDate);

        org.joda.time.LocalDateTime jodaDate = org.joda.time.LocalDateTime.now();
        printJoda(jodaMonth, "MMMM", jodaDate);
        printJoda(jodaMonthNumeric, "MM", jodaDate);
        printJoda(jodaDay, "EEEE", jodaDate);
        printJoda(jodaDayNumeric, "dd", jodaDate);
        printJoda(jodaYear, "yyyy", jodaDate);
        printJoda(jodaTime, "HH:mm:ss", jodaDate);
    }

    private void printThreeten(TextView tv, String pattern, TemporalAccessor accessor) {
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(pattern);
            String text = formatter.format(accessor);
            tv.setText(text);
        }
        catch (Exception e) {
            e.printStackTrace();
            tv.setText("exception");
        }
    }

    private void printJoda(TextView tv, String pattern, ReadablePartial partial) {
        try {
            org.joda.time.format.DateTimeFormatter formatter = DateTimeFormat.forPattern(pattern);
            String text = formatter.print(partial);
            tv.setText(text);
        }
        catch (Exception e) {
            e.printStackTrace();
            tv.setText("exception");
        }
    }

Good installations show output that looks like

    September
    09
    Tuesday
    06
    2016
    16:46:13

Bad installations show output that looks like

    September
    exception
    Tuesday
    exception
    0000
    exception

Both good and bad installations show the expected output when using the Joda methods.

When an exception is thrown, it is always of the form

    09-06 16:46:13.107 21689 21689 W System.err: org.threeten.bp.DateTimeException: Field HourOfDay cannot be printed as the value 1897781960 exceeds the maximum print width of 2
    09-06 16:46:13.107 21689 21689 W System.err: 	at org.threeten.bp.format.DateTimeFormatterBuilder$NumberPrinterParser.print(DateTimeFormatterBuilder.java:2361)
    09-06 16:46:13.107 21689 21689 W System.err: 	at org.threeten.bp.format.DateTimeFormatterBuilder$CompositePrinterParser.print(DateTimeFormatterBuilder.java:1995)
    09-06 16:46:13.107 21689 21689 W System.err: 	at org.threeten.bp.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1385)
    09-06 16:46:13.107 21689 21689 W System.err: 	at org.threeten.bp.format.DateTimeFormatter.format(DateTimeFormatter.java:1359)
    09-06 16:46:13.107 21689 21689 W System.err: 	at com.kayak.datetest.MainActivity.printThreeten(MainActivity.java:89)
    09-06 16:46:13.107 21689 21689 W System.err: 	at com.kayak.datetest.MainActivity.runOnce(MainActivity.java:75)

The test app shows these exceptions for the fields `MonthOfYear`, `DayOfMonth`, and `HourOfDay`. Only the fields required by the patterns posted above were tested.

It seems that the problem is not the `LocalDateTime` object itself; it always contains the expected information. Rather, the problem seems to lie in the `NumberPrinterParser` class, as the bad behavior is only exhibited when trying to print a numeric value. Text values work as expected even on bad installations.

I want to mention also that the `YearOfEra` field shows different bad behavior in these tests. Printing it never throws an exception, but bad installations print "0000" while good installations print "2016" as expected.

Mirroring @riggaroo's experience, placing a breakpoint on the `throw new DateTimeException(...)` line causes these problems to stop appearing. As soon as the breakpoint is removed, the problems come back.

I know there aren't any answers in this post, but I hope there might be a few new clues.

**Comment by gborland** [comment]
@benpm Do you see this happening only on Motorola devices?

**Comment by benpm** [comment]
@gborland yes, only Motorola. The vast majority of reports are for the MotoG3, which is the phone I used for my tests.

**Comment by syslogic** [comment]
[https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatterBuilder.html](DateTimeFormatterBuilder) reads: "This class is a mutable builder intended for use from a single thread."

**Comment by kenyee** [comment]
@jodastephen : was there a code change to fix this before closing the issue?  We still see this in the field w/ the latest version of the lib...(on Android on Moto devices)

**Comment by jodastephen** [comment]
No changes. I don't have any way to investigate or reproduce this. So, it is up to those affected to do so and suggest a PR I'm afraid.
